# Generated by Django 4.0.4 on 2022-06-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writtenmessage', models.CharField(max_length=255)),
                ('cipheredmessage', models.CharField(max_length=255)),
                ('decipheredmessage', models.CharField(max_length=255)),
            ],
        ),
    ]
